### PR TITLE
Adding CIP-1

### PR DESCRIPTION
**Pull request by galligan**

### CODE REVIEW

**Comment by galligan** [comment]
Committing for the moment and opening the draft request. This will help to track changes over time.

So far I've gotten up through `CIP types`.

**Comment by galligan** [comment]
@mattjoyal @joshfraser wanted to see if you had any thoughts, or if we can get this merged.

Thanks!

**Comment by mattjoyal** [comment]
Hey @galligan, this is looking great, I'm for getting this merged. I did have a comment to mention: 

- Regarding the section descriptions for cip-1.md & cip-template.md (e.g. Preamble, overview, goals/non-goals, etc). 
  - Merge the descriptions to match in the CIP template & CIP-1 to remove chance of confusion for `Background & Motivation`, `Goals / Non-goals`, and the other headers after that. 

That was the only thing so that we can get our first CIP out there and start the process.

**Comment by galligan** [comment]
> Merge the descriptions to match in the CIP template & CIP-1 to remove chance of confusion for Background & Motivation, Goals / Non-goals, and the other headers after that.

@mattjoyal good feedback. My reasoning for having different language is that in CIP-1 it's explanatory as to the purpose of the section. In the template it's more of a prompt. Do you feel strongly there should be parity between the two?

**Comment by mattjoyal** [comment]
@galligan - Going through it with that perspective I see what you mean. Only small detail I would add is to include a URL in the CIP-template to CIP-1 as an example or for more information, this way it is readily available, one click away. 

Regardless, I'm good to get this moved forward. It'd be good to announce CIP-1 in the town hall tomorrow too.

**Review by mattjoyal — APPROVED** [review]

**Review by myapdx — APPROVED** [review]

**Pull request merged**
