### PR TITLE
Add brand assets

### PR DESCRIPTION
**Pull request by galligan**

### CODE REVIEW

**Comment by mattjoyal** [comment]
Thoughts about adding a wordmark that has a transparent background?

**Comment by galligan** [comment]
@mattjoyal added them. Going to add you as a reviewer, and if you approve we can merge in.

**Comment by galligan** [comment]
Awesome thanks @mattjoyal. FYI typically the person who opened the PR is the one responsible to merge…in case there are any last minute things that need to be addressed. No reason for you to know that though, and we should come up with a guide on etiquette!

**Comment by mattjoyal** [comment]
Thanks, yeah it's been quite a while since I've done any PRs & merges - I'll keep that in mind for the next time through.

**Pull request merged**
